version: '3.1'

services:

  nextcloud:
    image: nextcloud:23.0.9-apache
    restart: "no"
    ports:
      - 667:80
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: db-nc
      NEXTCLOUD_ADMIN_USER: nextcloud
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_TRUSTED_DOMAINS: "localhost nextcloud"
    volumes:
      - nextcloud:/var/www/html

  wordpress:
    image: wordpress:6.0-apache
    restart: "no"
    ports:
      - 666:80
    environment:
      WORDPRESS_DB_HOST: db-wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html

  db-nc:
    image: mariadb:10.9.3
    restart: always
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-nc:/var/lib/mysql

  db-wp:
    image: mariadb:10.9.3
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-wp:/var/lib/mysql

volumes:
  nextcloud:
  wordpress:
  db-nc:
  db-wp:
